# Generated by Django 2.2 on 2019-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_rate',
            field=models.FloatField(),
        ),
    ]
