# Generated by Django 2.0.2 on 2018-03-18 14:41

from django.db import migrations, models
# from django.core.validators import validate_image_file_extension


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                # ('fileupload', models.ImageField(validators=
                # [validate_image_file_extension])),
                ('published_date',
                    models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
