# Generated by Django 2.0.2 on 2018-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Login',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True,
        #                                 primary_key=True,
        #                                 serialize=False,
        #                                 verbose_name='ID')),
        #         ('email', models.EmailField(max_length=100)),
        #         ('password', models.CharField(max_length=50)),
        #     ],
        # ),
    ]
