# Generated by Django 2.0.2 on 2018-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('myapp', '0004_merge_20180329_1251'),
        ('hello', '0004_merge_20180329_1251'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_name', models.CharField(max_length=100)),
        #         ('user_avatar', models.FileField(upload_to='')),
        #     ],
        # ),
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='latitude',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='longitude',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
